/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106550-g072101bd52-20220410"
#endif /* AVUTIL_FFVERSION_H */
