# https://www.baidu.com/more/
import requests
from lxml import etree

resp = requests.get('https://www.baidu.com/more/')
resp.encoding = 'utf-8'
html = resp.text
# print(html)
main_page = etree.HTML(html)
main_info = main_page.xpath('//*[@id="content"]/div')
# print(main_info)
for info in main_info:
    page_url = info.xpath('./div[2]/a/@href')
    web_name = info.xpath('./div[2]/a/text()')
    print(page_url, web_name, sep=',')


'''
['https://aiqicha.baidu.com/?from=allp'],['爱企查']
['https://dumall.baidu.com/?utm_source=baidu&utm_medium=all-products'],['小度商城']
['http://secr.baidu.com/'],['简单搜索']
['http://haokan.baidu.com'],['好看视频']
['http://yingxiao.baidu.com'],['百度营销中心']
['http://bit.baidu.com/'],['百度技术学院']
['https://quanmin.baidu.com/'],['度小视']
['https://aipage.baidu.com/'],['百度智能门户']
['https://aifanfan.baidu.com/'],['爱番番']
['http://e.baidu.com/ebaidu/home?refer=888'],['商业推广']
['https://pan.baidu.com/disk/main#/certification/web/introduction?from=header'],['百度网盘企业版']
['https://photo.baidu.com?from=bdcpdq'],['一刻相册']
['https://www.yoojia.com?sa=allp'],['有驾']
['https://jiankang.baidu.com/widescreen/home'],['百度健康']
[],[]
['http://fanyi-pro.baidu.com/?from=bdmore'],['百度人工翻译']
['http://www.baidu.com/'],['网页']
['http://video.baidu.com/'],['视频']
['http://fanyi.baidu.com/'],['百度翻译']
['http://map.baidu.com/'],['地图']
['http://news.baidu.com/'],['新闻']
['http://image.baidu.com/'],['图片']
['http://stu.baidu.com'],['百度识图']
['http://xueshu.baidu.com/ '],['百度学术']
['https://zhaopin.baidu.com?zp_fr=cpdq'],['百度百聘']
[],[]
['http://www.hao123.com/'],['hao123']
[],[]
['http://quzheng.baidu.com/'],['百度取证']
['http://baijiahao.baidu.com/'],['百家号']
['http://duer.baidu.com/'],['DUEROS']
['https://anquan.baidu.com/forum'],['百度安全社区']
['http://wenku.baidu.com/'],['文库']
['http://pan.baidu.com/'],['百度网盘']
['http://baike.baidu.com/'],['百科']
['http://tieba.baidu.com/'],['贴吧']
['http://zhidao.baidu.com/'],['知道']
['http://jingyan.baidu.com/'],['经验']
['https://www.dxmpay.com/'],['度小满支付']
['http://test.baidu.com'],['百度众测']
['https://www.combofin.com/?channel=baidumore'],['康波•财经']
['http://cbbs.baidu.com'],['百度社团赞助平台']
['http://baobao.baidu.com'],['宝宝知道']
['https://trust.baidu.com/'],['百度信誉']
['https://juejin.baidu.com'],['地图掘金']
['https://easylearn.baidu.com'],['百度教育']
[],[]
['http://game.91.com/'],['hao123游戏•手游']
['http://youxi.baidu.com/'],['百度游戏']
['http://app.baidu.com/'],['百度移动开放平台']
['https://g.baidu.com/'],['百度游戏开放平台']
[],[]
['http://h5.baidu.com/'],['百度 H5']
['https://8.duxiaoman.com/content/resource/app/index.html'],['度小满理财']
['http://srf.baidu.com'],['百度手机输入法']
['http://shouji.baidu.com'],['百度手机助手']
['http://fanyi.baidu.com/appdownload/download.html'],['百度翻译App']
['http://shoujiweishi.baidu.com/'],['百度手机卫士']
[],[]
['https://cdp.baidu.com'],['观星盘']
['http://ai.baidu.com/index/'],['百度大脑']
['http://open.baidu.com/'],['百度数据开放平台']
['http://zhanzhang.baidu.com/'],['百度搜索资源平台']
['http://tongji.baidu.com/'],['百度统计']
['http://union.baidu.com/'],['百度联盟']
['http://e.baidu.com?refer=889'],['百度营销']
['https://top.baidu.com/'],['百度热搜']
['http://index.baidu.com/'],['百度指数']
['http://mtj.baidu.com'],['百度移动统计']
['http://developer.baidu.com/'],['百度开发者中心']
['http://ce.baidu.com/?from=more'],['百度云观测']
['https://open2.baidu.com/'],['百度商业服务市场']
['http://yuqing.baidu.com/ '],['百度舆情']
['http://jingsuan.baidu.com'],['百度精算']
['https://su.baidu.com'],['百度云加速']
['https://cloud.baidu.com/'],['百度智能云']
['http://yuyin.baidu.com/'],['百度语音']
['http://ssp.baidu.com/'],['百度SSP媒体服务']
['http://push.baidu.com/'],['百度云推送']
['http://mtc.baidu.com/'],['百度移动云测试中心']
[],[]
['http://naotu.baidu.com'],['百度脑图工具']
['http://im.baidu.com/'],['如流']
['http://shurufa.baidu.com/'],['百度输入法']
['http://wubi.baidu.com/'],['百度五笔输入法']
[],[]
'''